version: '3.8'

services:
  streamer.devnet:
    container_name: streamer.devnet
    build:
      context: .
    networks:
      - devnet
    depends_on:
      - redis.devnet
    volumes:
      - type: bind
        source: ./docker-binds/config.jsonc
        target: /app/config.jsonc
        read_only: true
    command: /app/algostream -f /app/config.jsonc

  redis.devnet:
    container_name: redis.devnet
    image: 'redis:7-alpine'
    networks:
      - devnet
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host

  # Head to `http://localhost:8001` -- provide `redis.devnet` as a Target Host to browse (port: `6379`)
  insight.redis.devnet:
    container_name: insight.redis.devnet
    image: 'redislabs/redisinsight:1.13.1'
    ports:
      - target: 8001
        published: 8001
        protocol: tcp
        mode: host
    networks:
      - devnet
    depends_on:
      - redis.devnet

  # Browser: https://mqtt-explorer.com/
  mqtt.devnet:
    container_name: mqtt.devnet
    image: eclipse-mosquitto:2.0.15
    networks:
      - devnet
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./docker-binds/mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
        read_only: true
      # - type: bind
      #   source: mosquitto-data
      #   target: /mosquitto/data
      #   read_only: false

networks:
  devnet:

# volumes:
#   mosquitto-data:
